#%RAML 1.0 DataType
type: object
properties:
  number_of_patients_admitted_today :
    type : number
  number_of_patients_discharged_today :
    type : number
  number_of_patients_in_hospital :
    type : number