#%RAML 1.0 DataType
type: object
properties:
  
  Name:   
  
  Address:
  
  Age : 
   type : number
    
  
  Gender : 
   enum:
     - Male
     - Female
     - others
  
  PhoneNumber:
    type : number
    minimum : 1000000000
    maximum : 9999999999
    
  
  Email : 
   type : string
  
  BloodType:
    enum:
     - A+ve
     - B+ve
     - AB+ve
     - O+ve
     - A-ve
     - B-ve
     - AB-ve
     - O-ve
  
  Height :
    type : number

  Weight :
    type : number

  Disease :

  MedicalDetails:  
  
  Status :
    enum :
      - admitted
      





     
      
