httplistener :
 host : "localhost"
 port : "8081"
 

 
hostsql-db:
 host: "sql6.freemysqlhosting.net"
 username: "sql6463705"
 password: "QHPQ9p8m1Y"
 port: "3306"
 schema : "sql6463705"
 
cloudhub-login:
 username : "100503"
 password : "Irfan..ii1"
 environment : "Sandbox"
 workers : 1
 workerType : "Micro"
 applicationName: "hospital-management-api"
 muleVersion : 4.4.0