#%RAML 1.0
title: Hospital Managment System
description: This Project is the design of Hospital Managment Api's in which hospitals can register themeslves for patient services 
baseUri: www.hms.com
traits:
  error_traits : !include HMS_traits/errorcodes.raml
types:
   registerhospital_data_type : !include HMS_data_types/RegisterHospital.raml
   registerpatient_data_type : !include HMS_data_types/RegisterPatient.raml
   update_patient_details_by_hospital_data_type : !include HMS_data_types/UpdatePatientDetailsByHospital.raml
   update_patient_details_by_patient_data_type : !include HMS_data_types/UpdatePatientDetailsByPatient.raml
   dischargepatient_data_type : !include HMS_data_types/DischargePatient.raml
   hid_uri_parameter_data_type : !include HMS_data_types/Hid_uri_parameters.raml
   pid_uri_parameter_data_type : !include HMS_data_types/Pid_uri_parameters.raml

resourceTypes:
   rest_methods : !include HMS_resource_types/RestMethods_resource_type.raml
       

/hospital:
   /registerhospital: 
    description: /registerhospital is an API service provided for the Hospital Registration  
    post:
    type:
   
     rest_methods : {
      post_input : registerhospital_data_type,
      post-request-example : !include HMS_req_resp_examples/register_hospital_req_example.json,
      post-response-example : !include HMS_req_resp_examples/register_hospital_resp.json
    } 
    is:
      - error_traits
   

   /{hid}:
     uriParameters:
       hid_uri_parameter_data_type

       
     /deregisterhospital:
      delete:
       description: /registerhospital is an API service provided for the Hospital         De-Registration  
       queryParameters: 
          
            
      type:
          rest_methods : {delete-response-example: {"message" : "Hospital Deregistered"} } 
      is:
        - error_traits
 
     
     /admitpatient:
      post:
      description: /admitpatient is an API service provided for the Hospital to Register the Patient   
      type:
        rest_methods : {
          post_input : registerpatient_data_type,
          post-request-example: !include HMS_req_resp_examples/register_patient_req_example.json,
          post-response-example: !include HMS_req_resp_examples/register_hospital_resp.json

        } 
      is:
          - error_traits  
     /dischargepatient/{pid}:
       description: /dischargepatient is an API service provided for the Hospital to Update the Patient Admitted Status to Discharge  
       uriParameters:
        pid_uri_parameter_data_type

       patch:
       type:
         rest_methods : {
           patch_input : dischargepatient_data_type,
           patch-request-example: !include HMS_req_resp_examples/discharge_patient_req_example.json,
           patch-response-example: !include HMS_req_resp_examples/discharge_patient_resp.json

         }  
       is:
          - error_traits 

         
              

     /getallpatientsinfo:
       get:
       description: /getallpatients is an API service provided for the Hospital to get the information of all the Patients Registered to the Hospital  
       type:
        rest_methods : {
          get-response-example: !include HMS_req_resp_examples/get_all_patients_resp_example.json
        }
       is:
        - error_traits
         

                    
     /getpatientinfo/{pid}:
       description: /getpatientinfo is an API service provided for the Hospital to get the information of the particular Patients Registered to the Hospital 
       uriParameters:
        pid_uri_parameter_data_type
       get:
       type:
         rest_methods : {
           get-response-example: !include HMS_req_resp_examples/get_all_patients_resp_example.json
         }  
       is:
        - error_traits
  
     /updatepatientinfo/{pid}:
       description: /updatepatientinfo is an API service provided for the Hospital to update the information of the Patients Registered to the Hospital 
       uriParameters:
         pid_uri_parameter_data_type
       put:
       type:
         rest_methods : {
           patch_input : update_patient_details_by_hospital_data_type,
           patch-request-example: !include HMS_req_resp_examples/update_patient_details_by_hospital_req.json,
           patch-response-example: !include HMS_req_resp_examples/update_patient_details_by_hospital_resp.json

         }  
       is:
          - error_traits  

     /hospitalstats:
       get:
       description: /hospitalstats is an API service provided for the Hospital to view the information of admitted , discharge and total patient count on current day     
       type:
        rest_methods : {
          get-response-example: !include HMS_req_resp_examples/hospital_stats_resp.json
        }
       is:
        - error_traits         

/patient:  
 /searchhospital:
   get:
     description: /searchhospital is an API service provided for the Patients to search for the information of all Registered Hospital based on Name,Area,City of the hospitals
     queryParameters:
      Name?: string
      Area? : string
      City? : string
      
        
   type:
        rest_methods : {
          get-response-example: !include HMS_req_resp_examples/search_hospital_response.json
        }
   is:
        - error_traits 
  
   /sortbybeds:     
     get:
      description: /sortbybeds is an API service provided for the Patients to Sort the hospitals based on Beds Availability
      queryParameters:
       sortbybeds: 
        enum:
          - ascending
          - descending  
     
     type:
        rest_methods : {
          get-response-example: !include HMS_req_resp_examples/search_hospital_response.json
        }
     is:
        - error_traits
        
 
 /{hid}/update/{pid}:
   description: /update/{pid} is an API service provided for the Patients to Update their personal Information like Name,Address, gender etc..
   uriParameters:
     pid_uri_parameter_data_type
     hid_uri_parameter_data_type
   put:
   type:
         rest_methods : {
           patch_input : update_patient_details_by_patient_data_type,
           patch-request-example: !include HMS_req_resp_examples/update_patient_details_by_hospital_req.json,
           patch-response-example: !include HMS_req_resp_examples/update_patient_details_by_hospital_resp.json

         }  
   is:
          - error_traits 


  

        
       
  

